### ISSUE TITLE
default colors are not saveable

### ISSUE THREAD

**Issue by roman204** [Goomento/PageBuilder#15]
in goomento settings the "apply" button is always disabled, even if the colors are changed
![image](https://user-images.githubusercontent.com/584168/175025810-723d9cff-6889-427b-89b6-edc3bd5e7e62.png)

if i enable the button manually (remove the disabled attribute) and click it, the values are saved

**Comment by haihv433** [comment]
Thanks for sharing @roman204 
I will get more investigation on this, the fix will be release soon

**Comment by haihv433** [comment]
Hi @roman204 

I close this issue for now, pls checkout the new release of 0.3.1 and believe It was fixed
