### ISSUE TITLE
unable to access backend once after deploying goomento

### ISSUE THREAD

**Issue by Dereshp** [Goomento/PageBuilder#16]
Hi, 

currently using magento 2.4.3.  unable to access backend after deploying goomento

installation steps have been actioned as required and file permissions correctly set.

please refer error message

{"0":"Specified invalid parent id (Goomento_Core::menu)","1":"#1 Magento\\Backend\\Model\\Menu\\Config->_initMenu() called at [vendor\/magento\/module-backend\/Model\/Menu\/Config.php:116]\n#2 Magento\\Backend\\Model\\Menu\\Config->getMenu() called at [vendor\/magento\/module-backend\/Model\/Url.php:365]\n#3 Magento\\Backend\\Model\\Url->_getMenu() called at [vendor\/magento\/module-backend\/Model\/Url.php:325]\n#4 Magento\\Backend\\Model\\Url->getStartupPageUrl() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:187]\n#5 Magento\\Backend\\App\\AbstractAction->_processUrlKeys() called at [generated\/code\/Magento\/Backend\/Controller\/Adminhtml\/Index\/Index\/Interceptor.php:41]\n#6 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->_processUrlKeys() called at [vendor\/magento\/module-backend\/App\/Request\/BackendValidator.php:175]\n#7 Magento\\Backend\\App\\Request\\BackendValidator->validate() called at [vendor\/magento\/framework\/App\/Request\/CompositeValidator.php:40]\n#8 Magento\\Framework\\App\\Request\\CompositeValidator->validate() called at [vendor\/magento\/framework\/App\/FrontController.php:192]\n#9 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#10 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#11 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#12 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#13 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#14 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#15 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:23]\n#16 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#17 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]\n","url":"\/admin","script_name":"\/pub\/index.php","report_id":"8bef11b0d1fef21f8101c10f8ea32fb0b7ee8868f044124bbc499e547cbc316b"}

Please advise 

Thanks

**Comment by haihv433** [comment]
Hi @Dereshp 
Which version of Goomento are you using?

**Comment by haihv433** [comment]
Thanks @Dereshp 

Since this issue happened over and over in some instances, so, I will remove the Core menu to fix this

Pls wait for the next release

**Comment by Keglerass** [comment]
Documentation is not complete. On step "module:enable" enable addionally Goomento_Core and Goomento_DocBuilder.
`bin/magento module:enable Goomento_Core Goomento_PageBuilder Goomento_DocBuilder`

**Comment by haihv433** [comment]
So, you fixed this by also enabled a module `Goomento_Core` @Dereshp 

I will update the document

Thanks

**Comment by Dereshp** [comment]
Thanks 

I will attempt again

**Comment by haihv433** [comment]
Hi @Dereshp 

I close this issue for now, pls checkout the new release of 0.3.1

All old versions will be wiped out of repo in the short of time,
