### ISSUE TITLE
cannot install page-builder 0.3.2 beacause doc-builder requires 0.2.3

### ISSUE THREAD

**Issue by wjensen45xr** [Goomento/PageBuilder#17]
Hi there, 
when I try to install, I get this message : 

-----
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - goomento/module-doc-builder[1.0.2, ..., 1.0.3] require goomento/module-page-builder ^0.2.3 -> found goomento/module-page-builder[0.2.3, ..., 0.2.10] but it conflicts with your root composer.json require (^0.3.2).
    - goomento/module-page-builder 0.3.2 requires goomento/module-doc-builder ^1.0.2 -> satisfiable by goomento/module-doc-builder[1.0.2, 1.0.3].
    - Root composer.json requires goomento/module-page-builder ^0.3.2 -> satisfiable by goomento/module-page-builder[0.3.2].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
-----

Maybe it's just the module-doc-builder composer requirements that needs to be updated. 

Thanks

**Comment by haihv433** [comment]
Hi @wjensen45xr 
Thanks for your update

I updated the repo just now, 
Pls have a re-check 

Feel free to re-open this issue if It sill persisted
