### ISSUE TITLE
[question] hyva compatibility 

### ISSUE THREAD

**Issue by roman204** [Goomento/PageBuilder#19]
Hi again and thanks for your effort in this project. As currently the whole frontend for magento seems to change to hyva are you planning to make goomento compatible with it? That would be awesome.

**Comment by haihv433** [comment]
Hi @roman204 

Thanks for your recommendation, 

This is the first time I hear about Hyva, but It's on the trend then why not, I will deeply consider it to corporate with Hyva, but this process will take time and will not available soon, 

Make this project work with any kind of platforms that support Magento also set on the purpose at the first place, and I also happy to share any information to make that process faster,

**Comment by haihv433** [comment]
I closed this task
