### ISSUE TITLE
Support for PWA storefronts

### ISSUE THREAD

**Issue by seblindfors** [Goomento/PageBuilder#20]
Currently using a PWA storefront, the CMS page query returns the page HTML correctly, but the problem is that it's completely void of styling. Do you have any plans to implement support for PWA storefronts where the content is fetched with GraphQL?

**Comment by haihv433** [comment]
Hi @seblindfors 

Thanks for your suggestion, and yes, this module will soon available on GraphQL and Rest API, this also comes up with some new features about dealing with Private content which requires data on published API

Let wait for it,

**Comment by haihv433** [comment]
I closed this issue
