### ISSUE TITLE
Private Member In vendor/goomento/module-page-builder/Traits/TraitWidgetBlock.php

### ISSUE THREAD

**Issue by stevecantlay** [Goomento/PageBuilder#25]
After Installing v0.4.0 and the update Form Builder Module we have an issue with app/code/Goomento/PageBuilderForm/Block/Widgets/Form.php line 78 where static function self::parseSettingsByPrefix is called on Private Member as per private function parseSettingsByPrefix(string $prefix, array $settings) : array

**Comment by haihv433** [comment]
Hi @stevecantlay 

Pls update the Page Builder module to 0.4.1 

Let me know if still persist,

**Comment by stevecantlay** [comment]
resolved

**Comment by haihv433** [comment]
I'm closing this issue, glad to hear that solved your issue, 
Feel free to re-open this anytime,
