### ISSUE TITLE
Error after installing Goomento PageBuilder

### ISSUE THREAD

**Issue by Kiwifu** [Goomento/PageBuilder#26]
I am facing a problem with : Goomento PageBuilder

When I activate it and try to edit or create a page, I am getting this message : 

> Error: Class "Zend_Json" not found in /username/public_html/vendor/goomento/module-page-builder/Plugin/Framework/Data/Form/Element/Editor.php:78
Stack trace:
#0 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Goomento\PageBuilder\Plugin\Framework\Data\Form\Element\Editor->aroundGetElementHtml()
#1 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Block\Element\Editor\Interceptor->Magento\Framework\Interception\{closure}()
#2 /username/public_html/generated/code/Magento/PageBuilder/Block/Element/Editor/Interceptor.php(23): Magento\PageBuilder\Block\Element\Editor\Interceptor->___callPlugins()
#3 /username/public_html/vendor/magento/module-ui/Component/Form/Element/Wysiwyg.php(68): Magento\PageBuilder\Block\Element\Editor\Interceptor->getElementHtml()
#4 /username/public_html/vendor/magento/module-page-builder/Component/Form/Element/Wysiwyg.php(119): Magento\Ui\Component\Form\Element\Wysiwyg->__construct()
#5 /username/public_html/generated/code/Magento/PageBuilder/Component/Form/Element/Wysiwyg/Interceptor.php(14): Magento\PageBuilder\Component\Form\Element\Wysiwyg->__construct()
#6 /username/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\PageBuilder\Component\Form\Element\Wysiwyg\Interceptor->__construct()
#7 /username/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#8 /username/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#9 /username/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(261): Magento\Framework\ObjectManager\ObjectManager->create()
#10 /username/public_html/vendor/magento/module-ui/Component/Form/Field.php(85): Magento\Framework\View\Element\UiComponentFactory->create()
#11 /username/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(164): Magento\Ui\Component\Form\Field->prepare()
#12 /username/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent()
#13 /username/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent()
#14 /username/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(142): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent()
#15 /username/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(103): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent()
#16 /username/public_html/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\UiComponent->process()
#17 /username/public_html/vendor/magento/framework/View/Layout.php(365): Magento\Framework\View\Layout\GeneratorPool->process()
#18 /username/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(68): Magento\Framework\View\Layout->generateElements()
#19 /username/public_html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#20 /username/public_html/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#21 /username/public_html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#22 /username/public_html/vendor/magento/framework/View/Layout.php(271): Magento\Framework\View\Layout\Builder->build()
#23 /username/public_html/vendor/magento/framework/View/Layout.php(896): Magento\Framework\View\Layout->build()
#24 /username/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(293): Magento\Framework\View\Layout->getBlock()
#25 /username/public_html/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout\Interceptor->getBlock()
#26 /username/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(23): Magento\Backend\Model\View\Result\Page->setActiveMenu()
#27 /username/public_html/vendor/magento/module-cms/Controller/Adminhtml/Page/Edit.php(60): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu()
#28 /username/public_html/vendor/magento/module-cms/Controller/Adminhtml/Page/Edit.php(93): Magento\Cms\Controller\Adminhtml\Page\Edit->_initAction()
#29 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Cms\Controller\Adminhtml\Page\Edit->execute()
#30 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callParent()
#31 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#32 /username/public_html/generated/code/Magento/Cms/Controller/Adminhtml/Page/Edit/Interceptor.php(23): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callPlugins()
#33 /username/public_html/vendor/magento/framework/App/Action/Action.php(111): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->execute()
#34 /username/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#35 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#36 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callParent()
#37 /username/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#38 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#39 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#40 /username/public_html/generated/code/Magento/Cms/Controller/Adminhtml/Page/Edit/Interceptor.php(32): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callPlugins()
#41 /username/public_html/vendor/magento/framework/App/FrontController.php(245): Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->dispatch()
#42 /username/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#43 /username/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#44 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#45 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#46 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#47 /username/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#48 /username/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#49 /username/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#50 /username/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#51 /username/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#52 {main}

**Comment by Kiwifu** [comment]
> Error: Class "Zend_Filter_Input" not found in /username/public_html/vendor/goomento/module-page-builder/Helper/EscaperHelper.php:52
Stack trace:
#0 /username/public_html/vendor/goomento/module-page-builder/Controller/Adminhtml/Content/Save.php(39): Goomento\PageBuilder\Helper\EscaperHelper::filter()
#1 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Goomento\PageBuilder\Controller\Adminhtml\Content\Save->execute()
#2 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->___callParent()
#3 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->Magento\Framework\Interception\{closure}()
#4 /username/public_html/generated/code/Goomento/PageBuilder/Controller/Adminhtml/Content/Save/Interceptor.php(23): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->___callPlugins()
#5 /username/public_html/vendor/magento/framework/App/Action/Action.php(111): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->execute()
#6 /username/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#7 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#8 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->___callParent()
#9 /username/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->Magento\Framework\Interception\{closure}()
#10 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#11 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->Magento\Framework\Interception\{closure}()
#12 /username/public_html/generated/code/Goomento/PageBuilder/Controller/Adminhtml/Content/Save/Interceptor.php(32): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->___callPlugins()
#13 /username/public_html/vendor/magento/framework/App/FrontController.php(245): Goomento\PageBuilder\Controller\Adminhtml\Content\Save\Interceptor->dispatch()
#14 /username/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#15 /username/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#16 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#17 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#18 /username/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#19 /username/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#20 /username/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#21 /username/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#22 /username/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#23 /username/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#24 {main}

**Comment by haihv433** [comment]
Hi @Kiwifu 

which magento version and Goomento did you install?

**Comment by Kiwifu** [comment]
Hi dear,

Magento version : 2.4.6

Goomento : the latest version

**Comment by haihv433** [comment]
Hi @Kiwifu 
At the moment, this module did not support Magento version 2.4.6,
Please wait to the next release,

**Comment by Kiwifu** [comment]
Hi @haihv433 

Thank you for the reply.

Good luck.

**Comment by RBotfield** [comment]
Hi @haihv433, I've raised 2 PRs with the fix for Magento 2.4.6, where Zend_Json was removed in favor of Laminas\Json\Json

#28 
Goomento/PageBuilderApi#1

**Comment by haihv433** [comment]
Hi @RBotfield 

Thanks for PR,
I updated the code as your references

Pls have a check

**Comment by haihv433** [comment]
Hi @Kiwifu 

The module is now working with Magento 2.4.6 

Please try the newest version (0.4.3) at the time 

Thanks

**Comment by Kiwifu** [comment]
Great to know.

Thanks.
