### ISSUE TITLE
Deprecated Functionality: Creation of dynamic property Goomento\PageBuilder\Controller\Adminhtml\Ajax\BuilderAssistance\Interceptor::$responseDataStatusCode is deprecated in /srv/nginx/magento/vendor/goomento/module-core/Traits/TraitHttpAction.php on line 59

### ISSUE THREAD

**Issue by bonanzadigger** [Goomento/PageBuilder#29]
Hi,

we are using Magento CE 2.4.6 and getting this error after installing your latest free extension (master branch):

Deprecated Functionality: Creation of dynamic property Goomento\PageBuilder\Controller\Adminhtml\Ajax\BuilderAssistance\Interceptor::$responseDataStatusCode is deprecated in /srv/nginx/magento/vendor/goomento/module-core/Traits/TraitHttpAction.php on line 59

After disabling error_reporting, it works as expected, but this can't be a solution.
Thanks in advance for your support.
Cheers
peter

**Comment by haihv433** [comment]
Hi @bonanzadigger 

Thanks for caring, 

We're working on this issue,

**Comment by haihv433** [comment]
Hi @bonanzadigger 

This issue has been fixed in this tag https://github.com/Goomento/PageBuilder/tree/v0.4.4 

Please checkout our newest version see it work

Feel free to re-open this issue if it still persisted, 

Thanks.
