### ISSUE TITLE
Icon and Image Popup"s aren't working

### ISSUE THREAD

**Issue by christopher-abrams** [Goomento/PageBuilder#31]
Hi, we are using Magento 2.4.6 Version and the recent (0.4.4) version of this extension.

Unfortunately, the Icon Selection-Menu isn't displaying any icons and the Popup to select an image (for the image component for example), doesn't show up.

Screenshot of Icon Popup attached below.

![SCR-20230522-mhmr](https://github.com/Goomento/PageBuilder/assets/129730944/2da74ead-40a5-4b4e-a00b-f31cedf82ab7)

**Comment by haihv433** [comment]
Hi @christopher-abrams 

Thanks for let us know the issue, but unfortunately, I can not replicate your issue, 

Can you help me to open the Inspector, then copy here all the `error` message that you see, 

Btw, can you copy all the log that you see in file `var/log/pagebuilder/error.log` that located under your magento site 

Thanks

**Comment by haihv433** [comment]
Hi @christopher-abrams 

I located the issue of "Icon" popup did not working, and the fix will the release in very soon, 

But the issue "Image popup", can you more specific, such as

Can you click on Image thumbnail, and the image selector panel (will be slid from the left) did not appear? if so, can you open Inspector (after clicked in image thumbnail) then copy the message to here? 

Thanks

**Comment by haihv433** [comment]
Hi @christopher-abrams 

The issue has been fixed in this version https://github.com/Goomento/PageBuilder/releases/tag/v0.4.5

Please have a check on this, 

Feel free to open this if issue still persists

Thanks
