### ISSUE TITLE
Enable it in a custom module

### ISSUE THREAD

**Issue by VivekShingala** [Goomento/PageBuilder#32]
Hello

How can we enable Goomento for a custom module where we have description field (textarea)?

**Comment by haihv433** [comment]
Hi @VivekShingala 

FYI, By default Goomento might not show up in some editor, which created by custom module, 

but you can implement the Goomento by using the widget of WYSIWG Editor 

Document:  https://github.com/Goomento/PageBuilder/wiki/Guide:-Integrate-Buildable-Content#1-to-cms-pageblockproductcategory  

Hope this can help.

**Comment by haihv433** [comment]
Hi @VivekShingala 

I close this for now, feel free to open this back
