### ISSUE TITLE
Excellent page builder extension, would this work with hyva theme?

### ISSUE THREAD

**Issue by sajidpatel** [Goomento/PageBuilder#33]
Hi Guys,

I love the drag and drop page builder extension!

I was wondering if the frontend themes can be built with Hyva Themes?
Could the frontend theme be converted to tailwind and alpine js?

Thanks Guys

**Comment by haihv433** [comment]
Hi @sajidpatel 

Thanks for your feedback, that's great to hear you love it, 

About your question, I afraid the module did not work/compatible with Hyva Theme yet, 

This project still in free-to-use and no value returned yet, so It's hard to afford a license to use/develop in Hyva Theme, 

But guarantee that we will consider it when we have a chance.
