### ISSUE TITLE
Form validators

### ISSUE THREAD

**Issue by matt-o-matic** [Goomento/PageBuilder#36]
What form validations do you guys use?  It appears that types like email don't actually do any validation on the form input.  If this is true, I would say it is an implied bug... because why else would you have a specific type for email?

Are we to implement our own validators?  If so, where do we do that (I assume in the code)???

**Comment by haihv433** [comment]
Hi @matt-o-matic 

I answered via email, besides the Goomento Form Builder did not release in Goomento Page Builder open source, which is this project
