### ISSUE TITLE
Console Error: Uncaught Error: Script error for: jquery/ui

### ISSUE THREAD

**Issue by beendeluxe** [Goomento/PageBuilder#37]
We found your extended PageBuilder Extension and its really awesome. Thanks for developing!

But somehow we are getting some console errors when we enable your modules;
Frontend Console Error;
```
Uncaught Error: Script error for: jquery/ui
http://requirejs.org/docs/errors.html#scripterror
[require-min-file-resolver.min.js:16:53]
```
Backend Console Error (all ace/lib - marked as *);
```
Uncaught Error: Script error for "ace/lib/*"
http://requirejs.org/docs/errors.html#scripterror
[require.min.js:5:1795](/Goomento_PageBuilder/lib/requirejs/require.min.js)
```

We are using Magento 2.4.5-p4. Our Theme Developer mentioned that it may depends on deprecated call to 'jquery/ui'. 

Is this a known issue/bug? 

We would be happy if we can fix this.

**Comment by beendeluxe** [comment]
We would be able to temporary fix this error;

Find and Copy File: jquery-ui.min.js at pub/static/<theme>/frontend/<language>/jquery
Rename it to ui.min.js and paste it into the same directory above. 

We implemented this workaround by calling it within our theme directly. It will fix the error, but the warning is still there;
`Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site.`

For now all widgets from Builder are loading. 

It would be great, if there will be a fix coming with the next module update.

**Comment by haihv433** [comment]
Hi, 
Thanks for letting us know the issue 
we will fix this in the next release, Thanks
