### ISSUE TITLE
Question: how to set up Popup (Set section as a popup/modal) Feature

### ISSUE THREAD

**Issue by beendeluxe** [Goomento/PageBuilder#38]
Hey There,

we have a question about the extension. On your Widget List there i also an option to set up Popup/Modal section.

How to set up a section with modal/popup feature? So far we do not find any option for this. 

Hopeful that you could show how it works. 

Thanks.

**Comment by haihv433** [comment]
Hi @beendeluxe 

current module will not support Popup anymore, due to unprecedented issue, 
We will update the document
