### ISSUE TITLE
404 Not Found Editing Blocks ~ goomento-builder-assistance.js

### ISSUE THREAD

**Issue by steveshepherd** [Goomento/PageBuilder#42]
Magento 2.4.6p1, PHP 8.2

When editing/adding blocks through CONTENT > BLOCKS, the content no longer appears below as before.

`/static/adminhtml/Magento/backend/en_US/goomento-builder-assistance.js net::ERR_ABORTED 404 (Not Found)`

`console-output-handler.js:2 [2024-03-15 07:48:58] [ERROR] Failed to load the "goomento-builder-assistance" component.`

having searched through the entire code including the dependencies...this file (goomento-builder-assistance.js) does not appear to exist.

The remainder of the module appears to work perfectly well.

**Comment by haihv433** [comment]
Hi @steveshepherd 

Thanks for your submission, FYI, make sure your theme already merge this file https://github.com/Goomento/PageBuilder/blob/master/view/adminhtml/requirejs-config.js, if not it then will cause the issue as you described
