### ISSUE TITLE
Allow same Identifier if no store conflict

### ISSUE THREAD

**Issue by keyalita** [Goomento/PageBuilder#44]
Hi ! 

Could it be possible to match the native function of Magento pages with the identifier key ? 
Magento recommend to use different stores to manage multilang website. Natively, it allows you to have the same url key for multiple pages if it doesn't create a conflict (as long as the same url doesn't appear twice in the same store).
This feature allows to switch smoothly from one language to another without url redirection.

![image](https://github.com/Goomento/PageBuilder/assets/172027792/73c51015-21a7-433a-a7e4-1056f05c4d88)

Goomento's Pages & Landing Pages currently require a unique identifier that is not based on the store where it is displayed. 

![image](https://github.com/Goomento/PageBuilder/assets/172027792/b50b3403-648d-432c-bb36-b6e97030ec47)

**Comment by haihv433** [comment]
Hi @keyalita 
Thanks for let me know 
Will working on this and deliver it soon

**Comment by florianbeaupoilvnv** [comment]
Hi @haihv433 ,

It appears the issue is still present in version 0.5.2. 
Is it possible to reopen this issue and provide a fix for that please ?

**Comment by florianbeaupoilvnv** [comment]
Hi @haihv433,
Do you have any updates on this issue, please? Do you still support this module?
